# Generated by Django 5.2.6 on 2025-09-05 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pojazd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('kategoria', models.CharField(choices=[('motocykl', 'Motocykl'), ('osobowy', 'Osobowy'), ('ciezarowy', 'Ciężarowy')], max_length=10)),
                ('marka', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('rok_produkcji', models.PositiveIntegerField()),
                ('przebieg', models.PositiveIntegerField()),
                ('pojemnosc_skokowa', models.PositiveIntegerField()),
                ('rodzaj_paliwa', models.CharField(choices=[('benzyna', 'Benzyna'), ('diesel', 'Diesel'), ('lpg', 'LPG')], max_length=10)),
                ('data_dodania', models.DateField()),
                ('data_publikacji', models.DateField(null=True)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
