# Generated by Django 5.2.6 on 2025-09-14 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0003_pojazd_czy_usuniety'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zdjecie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zdjecie', models.ImageField(upload_to='zdjecia')),
            ],
        ),
        migrations.CreateModel(
            name='Pivot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czy_glowne', models.BooleanField(default=False)),
                ('pojazd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MotoSell.pojazd')),
                ('zdjecie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MotoSell.zdjecie')),
            ],
        ),
    ]
