# Generated by Django 5.2.6 on 2025-09-16 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0005_remove_pojazd_zdjecie'),
    ]

    operations = [
        migrations.AddField(
            model_name='zdjecie',
            name='czy_glowny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zdjecie',
            name='pojazd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MotoSell.pojazd'),
        ),
        migrations.DeleteModel(
            name='Pivot',
        ),
    ]
