# Generated by Django 5.2.6 on 2025-09-16 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0006_zdjecie_czy_glowny_zdjecie_pojazd_delete_pivot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zdjecie',
            name='pojazd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MotoSell.pojazd'),
        ),
    ]
