# Generated by Django 5.2.6 on 2025-09-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojazd',
            name='czy_opublikowany',
            field=models.BooleanField(default=False),
        ),
    ]
