# Generated by Django 5.2.6 on 2025-09-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0002_pojazd_czy_opublikowany'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojazd',
            name='czy_usuniety',
            field=models.BooleanField(default=False),
        ),
    ]
