# Generated by Django 5.2.6 on 2025-09-15 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0004_zdjecie_pivot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pojazd',
            name='zdjecie',
        ),
    ]
